### ISSUE TITLE
Update multiple individual Beacons with a single transaction | Airseeker

### ISSUE THREAD

**Issue by umersin61** [api3dao/airseeker-v1#216]
Currently the Airseeker updates each Beacon with an individual transaction. This is inefficient because the 21,000 base transaction gas cost is being paid for each update. We should instead batch these updates in a single transaction. This includes the development of a proxy Multicall contract that doesn’t revert if an individual update fails. See the thread for more information

https://api3workspace.slack.com/archives/C037NLX1R8T/p1653479838267289

**Comment by acenolaza** [comment]
![Image](https://user-images.githubusercontent.com/5776880/192015180-2323eb9c-37a8-460a-8160-3b84424fd2f6.png)

**Comment by acenolaza** [comment]
@bbenligiray since we already going to be making changes to DapiServer to support OEV, should't we also add the safe multicall function to the [ExtendedMulticall](https://github.com/api3dao/airnode-protocol-v1/blob/main/contracts/utils/ExtendedMulticall.sol#L8) contract instead of creating a new proxy contract?

**Comment by bbenligiray** [comment]
@acenolaza Good point, we should revisit that

**Comment by bbenligiray** [comment]
Created https://github.com/api3dao/airnode-protocol-v1/issues/19

**Comment by acenolaza** [comment]
Blocked by https://github.com/api3dao/airnode-protocol-v1/issues/19

**Comment by acenolaza** [comment]
~Blocked until new DapiServer with `tryMulticall()` is deployed~
