### ISSUE TITLE
Investigate & fix flaky E2E tests

### ISSUE THREAD

**Issue by amarthadan** [api3dao/airseeker-v1#224]
When I run E2E tests multiple times they sometimes pass and sometimes fail. This needs to be investigated and fixed.

**Comment by acenolaza** [comment]
@amarthadan I have some findings I'd like to share with you:

So this is not so easy to reproduce but once it fails then it keeps failing until the local eth node is restarted. 

When tests fail, this is the error that I see in the Airseeker logs: `[2022-09-02 16:15:50.061] WARN Failed attempt to update beacon. Error Error: processing response error (body="{\"jsonrpc\":\"2.0\",\"id\":63,\"error\":{\"code\":-32603,\"message\":\"Error: VM Exception while processing transaction: reverted with reason string 'Timestamp not valid'\"...`
This means the tx is reverted when it reaches [this line](https://github.com/api3dao/airnode-protocol-v1/blob/main/contracts/dapis/DapiServer.sol#L592) in the DapiServer contract.

~What's interesting is that I only see this error after 15 mins of having started the local eth node making the tx to fail. My best guess is that the mining options of the local hardhat eth node prevent the tx to be mined. I think we can either set the automine option in the [network config](https://github.com/api3dao/airseeker/blob/main/hardhat.config.ts#L4-L11) or maybe just somehow set the block timestamp manually before the [deployment.ts](https://github.com/api3dao/airseeker/blob/main/test/setup/deployment.ts#L251) script finishes.~

As stated in the UPDATE below, I now think the issue is that the update tx reverts with 'Timestamp not valid' because the local node gets reset to the original state causing the block.timestamp to be the same for each test and after a while this tx will obviously fail.

Another issue that I see is that we are retrying the tx whenever it fails but we are not increasing the nonce when the tx is reverted causing the nonce to be out-of-sync in the subsequent retries and also for the other beacoset updates that use the same sponsor wallet: https://github.com/api3dao/airseeker/blob/main/src/update-data-feeds.ts#L448-L468
This might also be an issue for beacon updates and my first reaction would be to override the `goOptions.retries` property with a value of 0;

UPDATE:
A new theory that I'm managing is that the hardhat reset [done before each](https://github.com/api3dao/airseeker/blob/main/test/e2e/airseeker.feature.ts#L42) test might be making the local eth node to reset the block timestamp to an old value causing the tx to revert 🤔

**Comment by amarthadan** [comment]
> When tests fail, this is the error that I see in the Airseeker logs: [2022-09-02 16:15:50.061] WARN Failed attempt to update beacon. Error Error: processing response error (body="{\"jsonrpc\":\"2.0\",\"id\":63,\"error\":{\"code\":-32603,\"message\":\"Error: VM Exception while processing transaction: reverted with reason string 'Timestamp not valid'\"...
This means the tx is reverted when it reaches [this line](https://github.com/api3dao/airnode-protocol-v1/blob/main/contracts/dapis/DapiServer.sol#L592) in the DapiServer contract.

> What's interesting is that I only see this error after 15 mins of having started the local eth node making the tx to fail. My best guess is that the mining options of the local hardhat eth node prevent the tx to be mined. I think we can either set the automine option in the [network config](https://github.com/api3dao/airseeker/blob/main/hardhat.config.ts#L4-L11) or maybe just somehow set the block timestamp manually before the [deployment.ts](https://github.com/api3dao/airseeker/blob/main/test/setup/deployment.ts#L251) script finishes.

Hmm. That might be a different issue. Take a look at some of the failing CI checks ([here](https://github.com/api3dao/airseeker/runs/8034401831?check_suite_focus=true) and [here](https://github.com/api3dao/airseeker/runs/8036647751?check_suite_focus=true) for example). These are the kind of flaky errors I had in mind. I'm pretty sure if you would restart them they will pass (since the PRs were passing before the merge).

Not sure that the problem you're describing is worth solving. As you said, it may be just the hardhat acting out.

> Another issue that I see is that we are retrying the tx whenever it fails but we are not increasing the nonce when the tx is reverted causing the nonce to be out-of-sync in the subsequent retries

I think we've discussed this previously and the consensus was that it's ok and the tx will be retried with a new nonce in the next cycle.

> and also for the other beacoset updates that use the same sponsor wallet: https://github.com/api3dao/airseeker/blob/main/src/update-data-feeds.ts#L448-L468

I don't think we've discussed that but I would assume it will be the same case and expected since we're processing beacon sets after the beacons (using the same sponsor wallet I mean).
@bbenligiray @aquarat any thoughts on this?

**Comment by aquarat** [comment]
Regarding `hardhat_reset`, if it's a race condition then perhaps the process should be (in `beforeEach`):
- reset the Hardhat node
- then query the Hardhat node on a timer/loop to confirm the network has actually reset
- and then only proceed?
This might be a good starting point to troubleshooting the other tests 🤷 

I hope `--runInBand` can be trusted 😬 

Regarding nonces: 
> I think we've discussed this previously and the consensus was that it's ok and the tx will be retried with a new nonce in the next cycle.

That's what I remember from that discussion. I think along these lines we said we'd divide beacons into batches and give each batch a unique sponsor to get a trade-off between on-chain dust and wallet independence/concurrent updates.

**Comment by bbenligiray** [comment]
Yes, there isn't really a better way of doing this, and using a dedicated sponsor per subscription-like task is the ultimate solution

**Comment by vponline** [comment]
Regarding the timestamp error, perhaps we should be setting the next block timestamp with:

```ts
beforeEach(async () => {
    // Reset the local hardhat network state for each test to prevent issues with other test contracts
    await hre.network.provider.send('hardhat_reset');
    // Set the net block timestamp to current time in seconds
    await hre.network.provider.send('evm_setNextBlockTimestamp', [Math.floor(Date.now() / 1000)]);
    // Mine the next block to set the timestamp for the following test
    await hre.network.provider.send('evm_mine');
...
```

**Comment by vponline** [comment]
I think there may be some interference from the `gas-oracle.feature.ts` tests with the rest. I removed the gas-oracle tests and ran the rest locally in a loop and didn't get any errors (including the timestamp change above)

So perhaps finishing #220 would be worth it?

**Comment by acenolaza** [comment]
The timestamp revert issue still happens when just running `airseeker.feature` tests so I think setting the `block.timestamp` to `Date.now()` like @vponline metioned [here](npx jest --selectProjects e2e --runInBand airseeker.feature) is still a really good idea 🥇 

As for the `gas-oracle.feature.ts` tests I have being able to reproduce it since we last discussed about it in today's weekly meeting.

**Comment by acenolaza** [comment]
Posting this message for future reference since the consensus is to not do anything about it:

About the nonce revert issue when beacon or beacon set update fails I think we should still set the reties to 0 if we are not going to increment the nonce on fail. I don't think it makes much sense to let the promise-utils.go() function keep retrying until timeout without incrementing the nonce (or at least check if nonce was used). @vponline any thoughts on this?
![image](https://user-images.githubusercontent.com/5776880/190225895-8ce9e2df-8c2c-4ef4-bf80-108105b3385f.png)

**Comment by amarthadan** [comment]
> About the nonce revert issue when beacon or beacon set update fails I think we should still set the reties to 0 if we are not going to increment the nonce on fail. I don't think it makes much sense to let the promise-utils.go() function keep retrying until timeout without incrementing the nonce (or at least check if nonce was used). @vponline any thoughts on this?

You would have to determine that it's failing with this specific error (nonce being out of order) and then stop retrying. Otherwise, you want to keep the retries in case of a network error or something unrelated that is recoverable.
