### ISSUE TITLE
Update signed data updates according to the changes in the DapiServer interface

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/airseeker-v1#327]
DapiServer signed data update interface changed a bit. Airseeker should be updated accordingly. There are two ways of doing this
- Do a breaking change
- Add a new trigger type that uses the new interface for backward/forward compatibility

**Comment by acenolaza** [comment]
After some analyzing, I'm thinking that breaking change option is the best option. Main reasons being:
1. Airseeker is already [importing DapiServerFactory](https://github.com/api3dao/airseeker/blob/main/src/update-data-feeds.ts#L126) from the airnode-protocol-v1 package. So once the new DapiServer contract is deployed and a new version of the package is released we'll need to update Airseeker dependencies. Then if we wanted to support both contract versions then we'll need to import one interface from airnode-protocol-v1 package and copy over the ABI json of the other contract (this might not be the case if we keep referencing the old package in package.json too but it sounds a bit messy).
2. Having a new trigger for using a different version of the same contract seems a bit odd because the contents of the new trigger will be the same. We could also modify the `chains.<chainId>.contracts` object to support `DapiServerV0` and `DapiServer` contract keys or do some other (breaking?) change like adding a `version` field to that object.
3. Airseeker is run by us so breaking changes deployment issues will be limited and we don't need to ask anyone to re-deploy.

@aquarat @bbenligiray WDYT? Am I missing something that makes supporting both contract versions necessary?

**Comment by acenolaza** [comment]
One more thing I've just realized is that some Airseeker e2e tests and scripts rely on `AccessControlRegistry.deriveRootRole() `function which will no longer exist in the new airnode-protocol-v1 release.

**Comment by aquarat** [comment]
A breaking change/no backwards compatibility seems fine to me - as you noted we're the only ones using this and we're not planning on using both contract versions in production. I don't think there's any business case to support both versions.

Even so, if we really need to we can run two Airseekers. @bbenligiray was of the opinion a while back that we'd take down the existing feeds at some point (I assume after switching over).

**Comment by bbenligiray** [comment]
The inconveniences look significant enough, I'm fine with a breaking change
