### ISSUE TITLE
Bug: filterEmptySponsors prevents beacon sets from being updated

### ISSUE THREAD

**Issue by aquarat** [api3dao/airseeker-v1#415]
Nodary largely operates single-source feeds.
The dAPIs team needs to run multi-source/aggregated feeds, this usually doesn't involve only updating single-source feeds.

The addition of this line in a recent commit causes Airseeker to exit early:
https://github.com/api3dao/airseeker/blob/7f0bd378e30062527bdb78afcf85707ae739c6b0/src/main.ts#L33

with the error "No beacons to fetch data for found. Stopping."

**Comment by bdrhn9** [comment]
Oh I found the problem causing this issue. Actually designed behaviour for `filterEmptySponsors` works as expected. However, designed behavior can be problematic because if all attempts failed while retrieving balance info for a funded sponsor, this sponsor isn't being included in config as if it's empty. That being said, this problem isn't related with feed type (beacon/beaconSet). Ways to go:

1. Don't change aforementioned behavior so count as it's empty sponsor if balance cannot be retrieved for it
2. Even if balance cannot be retrieved for a sponsor, add it to config

**Comment by aquarat** [comment]
Ah interesting my assumption was incorrect 👌 
It would probably be best to add it to the config anyway if all balance retrieval attempts fail - culling empty wallets is an optimisation.

**Comment by bbenligiray** [comment]
1 is more optimized and fails early, 2 is more resilient but that may hide the fact that filtering is failing. That being said, why is filtering failing? Because our batches are too large and the response takes too long?

**Comment by bdrhn9** [comment]
> 1 is more optimized and fails early, 2 is more resilient but that may hide the fact that filtering is failing. That being said, why is filtering failing? Because our batches are too large and the response takes too long?

Most probably it's related with bandwidth of the network that is being used for. When I'm trying to run Airseeker at home where my network runs on coaxial cable, Airseeker fails not only in filtering wallets but also in update cycle. When I'm at office where network flows on fiber cable, there is no problem with the same concurrency settings. I think it's not problem because bandwidth of AWS Lambda is high enough.

**Comment by bbenligiray** [comment]
Are you multicalling these yet?

**Comment by bdrhn9** [comment]
If you are meaning multicalling over contract, no we're not calling by that way.

**Comment by bbenligiray** [comment]
This probably happens due to the number of RPC calls and multicalling will resolve this issue anyway
